# Generated by Django 4.0.4 on 2022-07-15 15:17

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('author', models.CharField(max_length=200)),
                ('topic', models.CharField(max_length=200)),
                ('content', models.TextField(max_length=200000)),
                ('url', models.URLField()),
                ('likes', models.IntegerField(null=True)),
                ('comments', models.IntegerField(null=True)),
            ],
        ),
    ]
