# Generated by Django 4.0.4 on 2022-07-18 17:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0003_topics'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='url',
            field=models.ImageField(blank=True, upload_to='posts_images'),
        ),
    ]
