# Generated by Django 4.0.4 on 2022-07-18 17:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0004_alter_post_url'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='url_field',
            field=models.URLField(null=True),
        ),
    ]
