# Generated by Django 4.0.4 on 2022-07-18 17:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0005_post_url_field'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='url_field',
        ),
        migrations.AddField(
            model_name='post',
            name='image',
            field=models.ImageField(blank=True, upload_to='posts_images'),
        ),
        migrations.AlterField(
            model_name='post',
            name='url',
            field=models.URLField(null=True),
        ),
    ]
