# Generated by Django 4.0.4 on 2022-07-20 01:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0006_remove_post_url_field_post_image_alter_post_url'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='topic',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='posts.topics'),
        ),
    ]
